on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build CSUniverse
      run: dotnet build Fr.UnivArtois.CRIL.CSUniverse --configuration Release /p:Version=${VERSION}
    # - name: Test
    #   run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack CSUniverse
      run: dotnet pack Fr.UnivArtois.CRIL.CSUniverse --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push CSUniverse
      run: dotnet nuget push Fr.UnivArtois.CRIL.CSUniverse.${VERSION}.nupkg --source https://api.nuget.org --api-key ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}